name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: diffchecker_schema_test
          MYSQL_HOST: 127.0.0.1
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      RAILS_ENV: test
      DB_USERNAME: root
      DB_HOST: 127.0.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: init dotenv
        run: cp .env.example .env
      # Add or replace database setup steps here
      - name: Set up database schema
        run:  bin/rails db:schema:load && bin/rails db:migrate
      - name: run diffchecker schema
        run: script/diffchecker.sh
